### ISSUE TITLE
✨ NEW: Integration with `aiida-code-registry`?

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-project#1]
The `aiida-code-registry` is great tool for maintaining a repository of computers and codes from which users can directly install them. However, the way I'm using the registry is somewhat clunky: I click through it and try to find the computer/codeI want, click on "Raw" and copy the link. 

While doing this, I was considering we should perhaps have a CLI for accessing the registry. Some examples of usage below.

### Updating the registry

A command for syncing the latest information on computers and codes stored in the registry locally. This data can then be used by other commands.

```console
aiida-project registry update
```

### Listing computer/codes

```console
aiida-project registry list
```

To know which computers and codes are available, we need to list them. I think by default the list should be _both_ computers and codes, but in a one-liner for each.

### Installing computers/codes

```console
aiida-project registry install
```

Obviously, that's the whole point. Ideally you can just put the name. In case of ambiguity the command should raise.

## TODO

- [ ] Give the outputs some more thought.
- [ ] What other commands? E.g. `upload` to open a PR automatically with a new code.
- [ ] What conventions should we adopt on `aiida-code-registry` to make this work here? One thing that comes to mind is that how to install a code depends on the version of AiiDA.

**Comment by mbercx** [comment]
Pinging @yakutovicha @unkcpz for thoughts.
